#!/bin/bash
# ---------------------------------------------------------------------------
# This script installs files and services specific to the pi-imgtank.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/pi-imgtank
#
# ---------------------------------------------------------------------------

# --- basic packages   ------------------------------------------------------

apt update
apt install python3 python3-pip python3-pil libjpeg-dev zlib1g-dev libfreetype6-dev liblcms2-dev libopenjp2-7 libtiff5 git rsync -y

# --- install pibrella support-library   ------------------------------------

#pip install pibrella
pip3 install gpiozero
pip3 install luma.oled

# --- install specific files   ----------------------------------------------

rsync -avz $(dirname "$0")/../files/ /

# --- enable/restart services   ---------------------------------------------

systemctl enable endofboot.service
systemctl enable hat-pibrella-server.service
systemctl enable img_upload.path

systemctl start endofboot.service
systemctl start hat-pibrella-server.service
systemctl start img_upload.path
