#!/bin/bash
# ---------------------------------------------------------------------------
# This script installs lighttpd, php and a php-image gallery called
# photo_archive from http://thevdm.com.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/pi-imgtank
#
# ---------------------------------------------------------------------------

# --- basic packages   ------------------------------------------------------

apt-get -y install lighttpd php5-cgi php5-apcu php5-gd phpsysinfo

# --- configure php   --------------------------------------------------------

sed -i -e '/post_max_size/s/^.*post_max_size =.*/post_max_size = 64M/' \
  -e '/upload_max_filesize/s/^.*upload_max_filesize =.*/upload_max_filesize = 64M/' \
  -e '/upload_tmp_dir/s/^.*upload_tmp_dir =.*/upload_tmp_dir = \/data\/tmp/' \
        /etc/php5/cgi/php.ini

# --- install photo_archive   ------------------------------------------------

#wget http://thevdm.com/wp-content/uploads/2014/09/photo_archive_1.3.zip
#unzip photo_archive_1.3.zip -d /var/www/html/ photo_archive/
#rm -f photo_archive_1.3.zip

# we use our own copy (with minor mods)
PHOTO_ARCHIVE_ZIP=$(dirname "$0")/photo_archive_1.3_pi-imgtank.zip
unzip "$PHOTO_ARCHIVE_ZIP" -d /var/www/html/ photo_archive/*

# --- setup directories for the image-backup   -------------------------------

rm -fr /var/www/html/photo_archive/images
rm -fr /var/www/html/photo_archive/thumbs
ln -s /data/images /var/www/html/photo_archive/images
ln -s /data/thumbnails /var/www/html/photo_archive/thumbs

# --- setup directories for the image-upload   -------------------------------

mkdir -p /data/uploads /data/tmp
chown -R www-data:www-data /data/uploads /data/tmp

# --- setup status-page for the APC-cache and link phpsysinfo   --------------

ln -s /usr/share/doc/php5-apcu/apc.php /var/www/html
ln -s /usr/share/phpsysinfo /var/www/html/

# --- fix ownership   --------------------------------------------------------
chown -R www-data:www-data /var/www

# --- reload configuration   ------------------------------------------------

lighttpd-enable-mod fastcgi-php
/etc/init.d/lighttpd force-reload
